name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_apk:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: build debug apk
        run: flutter build apk --debug
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: cards-debug.apk
          path: ./build/app/outputs/flutter-apk/app-debug.apk
